defmodule PlaysteadWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :playstead

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # D-06: `http_only: true` and `same_site: "Lax"` always. Deliberately no
  # `:secure` key — `Plug.Conn.put_resp_cookie/4` sets `secure: true`
  # automatically, and only, when the request's own `conn.scheme` is
  # `:https` (never hard-forced, so a LAN plain-HTTP self-hoster is never
  # silently locked out). See `PlaysteadWeb.UserAuth`'s cookie options
  # comment for the full rationale.
  @session_options [
    store: :cookie,
    key: "_playstead_key",
    signing_salt: "+8AWZccK",
    same_site: "Lax",
    http_only: true
  ]

  # WR-01 (01-REVIEW.md): `:peer_data` is included so `SetupLive` can rate
  # limit the `verify_token` event per connect IP — the setup wizard's
  # token-verification step runs entirely over the LiveView socket with no
  # HTTP-pipeline throttle to fall back on.
  # `:user_agent` is included so `PlaysteadWeb.SandboxHook` can find the
  # Ecto sandbox owner a browser test stamped into it (test env only).
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :user_agent, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :user_agent, session: @session_options]]

  # Test-only: routes browser-driven requests onto the owning test's Ecto
  # sandbox connection. `:sql_sandbox` is set exclusively in config/test.exs
  # and read at compile time, so this plug does not exist in dev/prod builds.
  if Application.compile_env(:playstead, :sql_sandbox, false) do
    plug Phoenix.Ecto.SQL.Sandbox
  end

  @doc "The cookie session options, exposed so tests can mint real session cookies."
  def session_options, do: @session_options

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :playstead,
    gzip: not code_reloading?,
    only: PlaysteadWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :playstead
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PlaysteadWeb.Router
end
