import Config

# Configure your database
#
# `PLAYSTEAD_DEV_DATABASE_URL` is honored when set, so the containerized dev
# stack (`scripts/dev-up.sh` -> `docker-compose.dev.yml`) can point the app at
# its own `db` service instead of a Postgres on the developer's host. It is
# deliberately NOT named `DATABASE_URL`: that name carries production meaning in
# `config/runtime.exs` (where it is required and has no default), and a stray
# `DATABASE_URL` in a shell or CI environment must never silently redirect a
# native `mix phx.server` dev run. Unset -- the native path -- the discrete
# settings below apply unchanged.
case System.get_env("PLAYSTEAD_DEV_DATABASE_URL") do
  url when is_binary(url) and url != "" ->
    config :playstead, Playstead.Repo,
      url: url,
      stacktrace: true,
      show_sensitive_data_on_connection_error: true,
      pool_size: 10

  _ ->
    config :playstead, Playstead.Repo,
      username: "postgres",
      password: "postgres",
      hostname: "localhost",
      database: "playstead_dev",
      stacktrace: true,
      show_sensitive_data_on_connection_error: true,
      pool_size: 10
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to the loopback ipv4 address prevents access from other machines.
#
# `PLAYSTEAD_DEV_BIND_ALL=true` widens this to 0.0.0.0 and exists for exactly
# one caller: the dev container in `docker-compose.dev.yml`. Docker forwards a
# published port into the container's network namespace, so a server bound to
# the container's OWN loopback is unreachable from the host and the port mapping
# silently does nothing. This does NOT widen exposure on the host: that compose
# file publishes `127.0.0.1:4000:4000`, so the listening socket the host can
# reach is still loopback-only. Do not set this variable for a native run.
dev_bind_ip =
  if System.get_env("PLAYSTEAD_DEV_BIND_ALL") == "true",
    do: {0, 0, 0, 0},
    else: {127, 0, 0, 1}

config :playstead, PlaysteadWeb.Endpoint,
  http: [ip: dev_bind_ip],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "iOQh7+6AGzC1s+3MDiBBHV+J/Jw8UxnLfPVoLxhe9pU5SShLMOz/4OkDQNbMUyQ/",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:playstead, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:playstead, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for the LiveDashboard
config :playstead, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
