defmodule Playstead.Curation do
  @moduledoc """
  The user-scoped curation context (D-07…D-10): Favorites, Collections,
  the play queue, Continue dismissals, and coarse play sessions. Every
  public function takes the owning user id first and every query
  filters on it (T-03-11) — a curation row or its referenced asset set
  belonging to another user is never visible here, it is a 404.

  Every mutation follows the same discipline `Playstead.Idempotency`
  and `Playstead.Sync.ChangeJournal`'s moduledocs require: the row
  write and its journal entry (`ChangeJournal.append/4` or
  `tombstone/3`) happen inside one `Ecto.Multi`, never a separate
  transaction — a post-commit append could let a client miss the
  change permanently.

  The Mac client and the LiveView console both call this module; there
  is no second implementation of curation logic anywhere else.
  """

  import Ecto.Query, warn: false

  alias Playstead.Catalogue
  alias Playstead.Catalogue.AssetSet

  alias Playstead.Curation.{
    Collection,
    CollectionMember,
    ContinueDismissal,
    Favorite,
    PlaySession,
    Position,
    QueueItem
  }

  alias Playstead.Repo
  alias Playstead.Sync.{ChangeJournal, CurationPayload}

  # D-10's sanity caps: bound journal payload/snapshot growth, never
  # legitimately hit by a personal library.
  @collection_cap 500
  @member_cap 5000
  @queue_cap 500
  @default_recent_limit 50

  @doc """
  Favorites `asset_set_id` for `user_id`, using `id` as the row's
  client-supplied primary key. Idempotent by nature: a repeated intent
  (even under a different `id`) converges on the same row via the
  `(user_id, asset_set_id)` unique index and leaves exactly one row.
  Returns `{:error, :not_found}` if `asset_set_id` does not belong to
  `user_id`.
  """
  @spec add_favorite(pos_integer(), Ecto.UUID.t(), Ecto.UUID.t()) ::
          {:ok, Favorite.t()} | {:error, term()}
  def add_favorite(user_id, id, asset_set_id) do
    with :ok <- verify_asset_set_ownership(user_id, asset_set_id) do
      changeset =
        Favorite.create_changeset(%Favorite{}, %{
          id: id,
          user_id: user_id,
          asset_set_id: asset_set_id
        })

      # `returning: true` is load-bearing (mirrors Pairing.insert_credential/3's
      # D-20b comment): the primary key is client-supplied, not
      # autogenerated, so without an explicit RETURNING Ecto just hands
      # back the submitted changeset verbatim instead of the row that
      # actually persisted — on a conflict that would silently return
      # the caller's new id instead of the pre-existing row's.
      Ecto.Multi.new()
      |> Ecto.Multi.insert(:favorite, changeset,
        on_conflict: {:replace, [:updated_at]},
        conflict_target: [:user_id, :asset_set_id],
        returning: true
      )
      |> Ecto.Multi.run(:journal, fn _repo, %{favorite: favorite} ->
        ChangeJournal.append(user_id, :curation, favorite.id, CurationPayload.build(favorite))
      end)
      |> Repo.transaction()
      |> case do
        {:ok, %{favorite: favorite}} -> {:ok, favorite}
        {:error, _step, reason, _changes} -> {:error, reason}
      end
    end
  end

  @doc """
  Removes `user_id`'s favorite of `asset_set_id`, appending a tombstone
  journal entry with an empty payload in the same transaction.
  Removing a favorite that does not exist is accepted and treated as
  success (D-09's toggle idempotency) — there is nothing to tombstone,
  and nothing observable changes either way.
  """
  @spec remove_favorite(pos_integer(), Ecto.UUID.t()) :: {:ok, :removed} | {:error, term()}
  def remove_favorite(user_id, asset_set_id) do
    case get_by_safe(Favorite, user_id: user_id, asset_set_id: asset_set_id) do
      nil ->
        {:ok, :removed}

      %Favorite{} = favorite ->
        Ecto.Multi.new()
        |> Ecto.Multi.delete(:favorite, favorite)
        |> Ecto.Multi.run(:journal, fn _repo, %{favorite: favorite} ->
          ChangeJournal.tombstone(user_id, :curation, favorite.id)
        end)
        |> Repo.transaction()
        |> case do
          {:ok, _changes} -> {:ok, :removed}
          {:error, _step, reason, _changes} -> {:error, reason}
        end
    end
  end

  @doc "Lists `user_id`'s favorites, oldest row-id first."
  @spec list_favorites(pos_integer()) :: [Favorite.t()]
  def list_favorites(user_id) do
    from(f in Favorite, where: f.user_id == ^user_id, order_by: [asc: f.id])
    |> Repo.all()
  end

  ## Collections (D-10)

  @doc """
  Creates a manual collection named `name` (sanitized per
  `Playstead.Catalogue.sanitize_title/1`) at the end of `user_id`'s
  collection list. `id` is the row's client-supplied primary key.
  Returns `{:error, {:curation_limit_exceeded, _}}` at the #{@collection_cap}-collection cap.
  """
  @spec create_collection(pos_integer(), Ecto.UUID.t(), String.t()) ::
          {:ok, Collection.t()} | {:error, term()}
  def create_collection(user_id, id, name) do
    # P5-WR-001: the cap check and the insert used to be a plain
    # read-then-write outside any lock, so two concurrent requests from
    # the same user's paired devices could both read a count under the
    # cap and both insert. Take a per-user advisory lock for the
    # duration of this transaction so a concurrent cap check/insert for
    # the same user serializes behind it instead of racing.
    Ecto.Multi.new()
    |> Ecto.Multi.run(:lock, fn repo, _changes -> acquire_cap_lock(repo, :collection, user_id) end)
    |> Ecto.Multi.run(:cap, fn _repo, _changes ->
      as_multi_result(check_collection_cap(user_id))
    end)
    |> Ecto.Multi.insert(:collection, fn _changes ->
      position = Position.last(max_position(Collection, user_id: user_id))

      Collection.create_changeset(%Collection{}, %{
        id: id,
        user_id: user_id,
        name: Catalogue.sanitize_title(name),
        position: position
      })
    end)
    |> Ecto.Multi.run(:journal, fn _repo, %{collection: collection} ->
      ChangeJournal.append(user_id, :curation, collection.id, CurationPayload.build(collection))
    end)
    |> Repo.transaction()
    |> case do
      {:ok, %{collection: collection}} -> {:ok, collection}
      {:error, _step, reason, _changes} -> {:error, reason}
    end
  end

  @doc "Renames `collection_id` (owned by `user_id`); sanitizes `name` the same way creation does."
  @spec rename_collection(pos_integer(), Ecto.UUID.t(), String.t()) ::
          {:ok, Collection.t()} | {:error, term()}
  def rename_collection(user_id, collection_id, name) do
    with {:ok, collection} <- verify_collection_ownership(user_id, collection_id) do
      changeset = Collection.rename_changeset(collection, %{name: Catalogue.sanitize_title(name)})

      Ecto.Multi.new()
      |> Ecto.Multi.update(:collection, changeset)
      |> Ecto.Multi.run(:journal, fn _repo, %{collection: collection} ->
        ChangeJournal.append(user_id, :curation, collection.id, CurationPayload.build(collection))
      end)
      |> Repo.transaction()
      |> case do
        {:ok, %{collection: collection}} -> {:ok, collection}
        {:error, _step, reason, _changes} -> {:error, reason}
      end
    end
  end

  @doc """
  Deletes `collection_id` (owned by `user_id`) and every member row it
  contains, tombstoning each. Deleting an already-deleted or
  never-existing collection is accepted and treated as success.
  """
  @spec delete_collection(pos_integer(), Ecto.UUID.t()) :: {:ok, :removed} | {:error, term()}
  def delete_collection(user_id, collection_id) do
    case get_by_safe(Collection, id: collection_id, user_id: user_id) do
      nil ->
        {:ok, :removed}

      %Collection{} = collection ->
        Repo.transaction(fn ->
          members =
            from(m in CollectionMember, where: m.collection_id == ^collection.id) |> Repo.all()

          Enum.each(members, fn member ->
            Repo.delete!(member)
            {:ok, _entry} = ChangeJournal.tombstone(user_id, :curation, member.id)
          end)

          Repo.delete!(collection)
          {:ok, _entry} = ChangeJournal.tombstone(user_id, :curation, collection.id)
          :removed
        end)
        |> case do
          {:ok, :removed} -> {:ok, :removed}
          {:error, reason} -> {:error, reason}
        end
    end
  end

  @doc "Lists `user_id`'s collections in display order."
  @spec list_collections(pos_integer()) :: [Collection.t()]
  def list_collections(user_id) do
    from(c in Collection, where: c.user_id == ^user_id, order_by: [asc: c.position])
    |> Repo.all()
  end

  @doc """
  Lists `collection_id`'s members in order, scoped to `user_id`.
  Returns `{:error, :not_found}` if the collection is not owned by
  `user_id`. An empty collection returns `{:ok, []}`.
  """
  @spec list_collection_members(pos_integer(), Ecto.UUID.t()) ::
          {:ok, [CollectionMember.t()]} | {:error, term()}
  def list_collection_members(user_id, collection_id) do
    with {:ok, _collection} <- verify_collection_ownership(user_id, collection_id) do
      members =
        from(m in CollectionMember,
          where: m.collection_id == ^collection_id,
          order_by: [asc: m.position]
        )
        |> Repo.all()

      {:ok, members}
    end
  end

  @doc """
  Adds `asset_set_id` to `collection_id` (owned by `user_id`) at the
  end of its member list. Idempotent: re-adding an already-present
  member converges on the existing row via the `(collection_id,
  asset_set_id)` unique index. Returns `{:error, :not_found}` if
  either the collection or the asset set is not owned by `user_id`,
  and `{:error, {:curation_limit_exceeded, _}}` at the #{@member_cap}-member cap.
  """
  @spec add_collection_member(pos_integer(), Ecto.UUID.t(), Ecto.UUID.t(), Ecto.UUID.t()) ::
          {:ok, CollectionMember.t()} | {:error, term()}
  def add_collection_member(user_id, collection_id, id, asset_set_id) do
    with {:ok, collection} <- verify_collection_ownership(user_id, collection_id),
         :ok <- verify_asset_set_ownership(user_id, asset_set_id) do
      # P5-WR-001: lock per-collection so two concurrent adds to the same
      # collection can't both observe a stale under-cap count.
      Ecto.Multi.new()
      |> Ecto.Multi.run(:lock, fn repo, _changes ->
        acquire_cap_lock(repo, :collection_member, collection.id)
      end)
      |> Ecto.Multi.run(:cap, fn _repo, _changes ->
        as_multi_result(check_member_cap(collection.id, asset_set_id))
      end)
      |> Ecto.Multi.insert(
        :member,
        fn _changes ->
          position = Position.last(max_position(CollectionMember, collection_id: collection.id))

          CollectionMember.create_changeset(%CollectionMember{}, %{
            id: id,
            user_id: user_id,
            collection_id: collection.id,
            asset_set_id: asset_set_id,
            position: position
          })
        end,
        on_conflict: {:replace, [:updated_at]},
        conflict_target: [:collection_id, :asset_set_id],
        returning: true
      )
      |> Ecto.Multi.run(:journal, fn _repo, %{member: member} ->
        ChangeJournal.append(user_id, :curation, member.id, CurationPayload.build(member))
      end)
      |> Repo.transaction()
      |> case do
        {:ok, %{member: member}} -> {:ok, member}
        {:error, _step, reason, _changes} -> {:error, reason}
      end
    end
  end

  @doc "Removes `asset_set_id` from `collection_id` (owned by `user_id`); a no-op if absent."
  @spec remove_collection_member(pos_integer(), Ecto.UUID.t(), Ecto.UUID.t()) ::
          {:ok, :removed} | {:error, term()}
  def remove_collection_member(user_id, collection_id, asset_set_id) do
    with {:ok, _collection} <- verify_collection_ownership(user_id, collection_id) do
      case Repo.get_by(CollectionMember, collection_id: collection_id, asset_set_id: asset_set_id) do
        nil ->
          {:ok, :removed}

        %CollectionMember{} = member ->
          Ecto.Multi.new()
          |> Ecto.Multi.delete(:member, member)
          |> Ecto.Multi.run(:journal, fn _repo, %{member: member} ->
            ChangeJournal.tombstone(user_id, :curation, member.id)
          end)
          |> Repo.transaction()
          |> case do
            {:ok, _changes} -> {:ok, :removed}
            {:error, _step, reason, _changes} -> {:error, reason}
          end
      end
    end
  end

  @doc """
  Moves `asset_set_id` within `collection_id` (owned by `user_id`) to
  sit between the members named by `neighbours`'
  `:before_asset_set_id`/`:after_asset_set_id` (either may be `nil`
  for "start"/"end" of the list). The unit of truth is this one row's
  position, never a submitted ordered list. Rebalances the whole
  collection first, inside the same transaction, if the neighbours are
  out of representable precision. A neighbour naming another user's
  row (or a row outside this collection) returns `{:error, :not_found}`.
  Moving to the position a member already occupies is a no-op.
  """
  @spec move_collection_member(pos_integer(), Ecto.UUID.t(), Ecto.UUID.t(), map()) ::
          {:ok, CollectionMember.t()} | {:error, term()}
  def move_collection_member(user_id, collection_id, asset_set_id, neighbours) do
    before_id = Map.get(neighbours, :before_asset_set_id)
    after_id = Map.get(neighbours, :after_asset_set_id)

    with {:ok, _collection} <- verify_collection_ownership(user_id, collection_id),
         {:ok, member} <- fetch_collection_member(collection_id, asset_set_id) do
      # P5-WR-005: the whole read-resolve-write sequence runs inside one
      # transaction, guarded by a per-collection advisory lock, so a
      # concurrent move on the same collection blocks until this one
      # commits rather than computing/writing a position from a stale
      # read of the neighbours.
      Repo.transaction(fn ->
        with :ok <- lock_resource!(:collection_member, collection_id),
             {:ok, before_pos} <- resolve_member_neighbour(collection_id, before_id),
             {:ok, after_pos} <- resolve_member_neighbour(collection_id, after_id),
             :ok <- validate_neighbour_order(before_pos, after_pos) do
          result =
            if before_pos && after_pos && Position.needs_rebalance?(before_pos, after_pos) do
              with {:ok, _rebalanced} <- do_rebalance_collection(user_id, collection_id),
                   {:ok, before_pos2} <- resolve_member_neighbour(collection_id, before_id),
                   {:ok, after_pos2} <- resolve_member_neighbour(collection_id, after_id),
                   :ok <- validate_neighbour_order(before_pos2, after_pos2) do
                reposition_member(user_id, member, Position.between(before_pos2, after_pos2))
              end
            else
              reposition_member(user_id, member, Position.between(before_pos, after_pos))
            end

          case result do
            {:ok, updated} -> updated
            {:error, reason} -> Repo.rollback(reason)
          end
        else
          {:error, reason} -> Repo.rollback(reason)
        end
      end)
    end
  end

  @doc """
  Reassigns evenly spaced positions across `collection_id`'s members
  (owned by `user_id`), preserving the current visible order, and
  journals one entry per row whose position actually changed.
  """
  @spec rebalance_collection(pos_integer(), Ecto.UUID.t()) ::
          {:ok, [CollectionMember.t()]} | {:error, term()}
  def rebalance_collection(user_id, collection_id) do
    Repo.transaction(fn ->
      case do_rebalance_collection(user_id, collection_id) do
        {:ok, members} -> members
        {:error, reason} -> Repo.rollback(reason)
      end
    end)
  end

  ## The play queue (D-07/D-09) — one per user, a backlog/watchlist.

  @doc """
  Enqueues `asset_set_id` for `user_id` at the end of the queue. `id`
  is the row's client-supplied primary key. Idempotent: re-enqueuing
  an already-queued game converges on the existing row. Returns
  `{:error, {:curation_limit_exceeded, _}}` at the #{@queue_cap}-item cap.
  """
  @spec enqueue(pos_integer(), Ecto.UUID.t(), Ecto.UUID.t()) ::
          {:ok, QueueItem.t()} | {:error, term()}
  def enqueue(user_id, id, asset_set_id) do
    with :ok <- verify_asset_set_ownership(user_id, asset_set_id) do
      # P5-WR-001: lock per-user so two concurrent enqueues (e.g. from
      # two paired devices) can't both observe a stale under-cap count.
      Ecto.Multi.new()
      |> Ecto.Multi.run(:lock, fn repo, _changes -> acquire_cap_lock(repo, :queue, user_id) end)
      |> Ecto.Multi.run(:cap, fn _repo, _changes ->
        as_multi_result(check_queue_cap(user_id, asset_set_id))
      end)
      |> Ecto.Multi.insert(
        :item,
        fn _changes ->
          position = Position.last(max_position(QueueItem, user_id: user_id))

          QueueItem.create_changeset(%QueueItem{}, %{
            id: id,
            user_id: user_id,
            asset_set_id: asset_set_id,
            position: position
          })
        end,
        on_conflict: {:replace, [:updated_at]},
        conflict_target: [:user_id, :asset_set_id],
        returning: true
      )
      |> Ecto.Multi.run(:journal, fn _repo, %{item: item} ->
        ChangeJournal.append(user_id, :curation, item.id, CurationPayload.build(item))
      end)
      |> Repo.transaction()
      |> case do
        {:ok, %{item: item}} -> {:ok, item}
        {:error, _step, reason, _changes} -> {:error, reason}
      end
    end
  end

  @doc "Removes `asset_set_id` from `user_id`'s queue; a no-op if absent."
  @spec dequeue(pos_integer(), Ecto.UUID.t()) :: {:ok, :removed} | {:error, term()}
  def dequeue(user_id, asset_set_id) do
    case get_by_safe(QueueItem, user_id: user_id, asset_set_id: asset_set_id) do
      nil ->
        {:ok, :removed}

      %QueueItem{} = item ->
        Ecto.Multi.new()
        |> Ecto.Multi.delete(:item, item)
        |> Ecto.Multi.run(:journal, fn _repo, %{item: item} ->
          ChangeJournal.tombstone(user_id, :curation, item.id)
        end)
        |> Repo.transaction()
        |> case do
          {:ok, _changes} -> {:ok, :removed}
          {:error, _step, reason, _changes} -> {:error, reason}
        end
    end
  end

  @doc "Lists `user_id`'s queue in order."
  @spec list_queue(pos_integer()) :: [QueueItem.t()]
  def list_queue(user_id) do
    from(i in QueueItem, where: i.user_id == ^user_id, order_by: [asc: i.position])
    |> Repo.all()
  end

  @doc """
  Moves `asset_set_id` in `user_id`'s queue to sit between the items
  named by `neighbours`' `:before_asset_set_id`/`:after_asset_set_id`
  — same contract as `move_collection_member/4`.
  """
  @spec move_queue_item(pos_integer(), Ecto.UUID.t(), map()) ::
          {:ok, QueueItem.t()} | {:error, term()}
  def move_queue_item(user_id, asset_set_id, neighbours) do
    before_id = Map.get(neighbours, :before_asset_set_id)
    after_id = Map.get(neighbours, :after_asset_set_id)

    with {:ok, item} <- fetch_queue_item(user_id, asset_set_id) do
      # P5-WR-005: same per-resource advisory lock discipline as
      # `move_collection_member/4` — the whole read-resolve-write
      # sequence runs inside one transaction guarded by a per-user
      # queue lock.
      Repo.transaction(fn ->
        with :ok <- lock_resource!(:queue, user_id),
             {:ok, before_pos} <- resolve_queue_neighbour(user_id, before_id),
             {:ok, after_pos} <- resolve_queue_neighbour(user_id, after_id),
             :ok <- validate_neighbour_order(before_pos, after_pos) do
          result =
            if before_pos && after_pos && Position.needs_rebalance?(before_pos, after_pos) do
              with {:ok, _rebalanced} <- do_rebalance_queue(user_id),
                   {:ok, before_pos2} <- resolve_queue_neighbour(user_id, before_id),
                   {:ok, after_pos2} <- resolve_queue_neighbour(user_id, after_id),
                   :ok <- validate_neighbour_order(before_pos2, after_pos2) do
                reposition_queue_item(user_id, item, Position.between(before_pos2, after_pos2))
              end
            else
              reposition_queue_item(user_id, item, Position.between(before_pos, after_pos))
            end

          case result do
            {:ok, updated} -> updated
            {:error, reason} -> Repo.rollback(reason)
          end
        else
          {:error, reason} -> Repo.rollback(reason)
        end
      end)
    end
  end

  @doc """
  Reassigns evenly spaced positions across `user_id`'s whole queue,
  preserving the current visible order, journaling one entry per row
  whose position actually changed.
  """
  @spec rebalance_queue(pos_integer()) :: {:ok, [QueueItem.t()]} | {:error, term()}
  def rebalance_queue(user_id) do
    Repo.transaction(fn ->
      case do_rebalance_queue(user_id) do
        {:ok, items} -> items
        {:error, reason} -> Repo.rollback(reason)
      end
    end)
  end

  ## Play sessions, Recent, and Continue (D-07)

  @doc """
  Records a coarse play session for `user_id`. `attrs` (string or atom
  keys) must include `:id`/`"id"`, `:asset_set_id`/`"asset_set_id"`,
  and `:started_at`/`"started_at"`; `:ended_at`/`"ended_at"` is
  optional. Posting the same session `id` twice leaves one row and
  returns success -- nothing on this path ever gates, delays, or fails
  a launch, so the Mac outbox can post at its own pace.

  Re-derives and re-journals the compact `recent` summary for the
  session's game in the same transaction (`journal_recent/2`), keyed
  by the game's `asset_set_id` rather than the session's own id, so a
  resuming client reconstructs Recent from the journal alone without
  fetching full session history.
  """
  @spec record_play_session(pos_integer(), map()) :: {:ok, PlaySession.t()} | {:error, term()}
  def record_play_session(user_id, attrs) do
    asset_set_id = Map.get(attrs, :asset_set_id) || Map.get(attrs, "asset_set_id")

    with :ok <- verify_asset_set_ownership(user_id, asset_set_id) do
      changeset =
        PlaySession.create_changeset(
          %PlaySession{},
          Map.merge(attrs, %{user_id: user_id, asset_set_id: asset_set_id})
        )

      Ecto.Multi.new()
      |> Ecto.Multi.insert(:session, changeset, on_conflict: :nothing, conflict_target: [:id])
      |> Ecto.Multi.run(:journal, fn _repo, _changes -> journal_recent(user_id, asset_set_id) end)
      |> Repo.transaction()
      |> case do
        {:ok, %{session: session}} -> {:ok, session}
        {:error, _step, reason, _changes} -> {:error, reason}
      end
    end
  end

  @doc """
  Deletes `session_id` (owned by `user_id`) and re-derives the
  `recent` summary for its game -- tombstoning that game's `recent`
  entity entirely if no session remains for it. A no-op if the session
  does not exist.
  """
  @spec delete_play_session(pos_integer(), Ecto.UUID.t()) :: {:ok, :removed} | {:error, term()}
  def delete_play_session(user_id, session_id) do
    case get_by_safe(PlaySession, id: session_id, user_id: user_id) do
      nil ->
        {:ok, :removed}

      %PlaySession{asset_set_id: asset_set_id} = session ->
        Repo.transaction(fn ->
          Repo.delete!(session)

          remaining? =
            Repo.exists?(
              from(s in PlaySession,
                where: s.user_id == ^user_id and s.asset_set_id == ^asset_set_id
              )
            )

          result =
            if remaining? do
              journal_recent(user_id, asset_set_id)
            else
              ChangeJournal.tombstone(user_id, :curation, asset_set_id)
            end

          case result do
            {:ok, _entry} -> :removed
            {:error, reason} -> Repo.rollback(reason)
          end
        end)
        |> case do
          {:ok, :removed} -> {:ok, :removed}
          {:error, reason} -> {:error, reason}
        end
    end
  end

  @doc """
  Lists `user_id`'s Recent games: one entry per distinct asset set, the
  latest session start per game, ordered descending, limited to
  `opts[:limit]` (default #{@default_recent_limit}).
  """
  @spec list_recent(pos_integer(), keyword()) :: [
          %{asset_set_id: Ecto.UUID.t(), last_played_at: DateTime.t()}
        ]
  def list_recent(user_id, opts \\ []) do
    limit = Keyword.get(opts, :limit, @default_recent_limit)

    from(s in PlaySession,
      where: s.user_id == ^user_id,
      group_by: s.asset_set_id,
      select: %{asset_set_id: s.asset_set_id, last_played_at: max(s.started_at)},
      order_by: [desc: max(s.started_at)],
      limit: ^limit
    )
    |> Repo.all()
  end

  @doc """
  Lists `user_id`'s Continue games: Recent minus games explicitly
  dismissed, except a game whose most recent session started after
  its dismissal is restored automatically (playing a dismissed game
  again returns it to Continue with no explicit undismiss needed).
  """
  @spec list_continue(pos_integer()) :: [
          %{asset_set_id: Ecto.UUID.t(), last_played_at: DateTime.t()}
        ]
  def list_continue(user_id) do
    dismissed_at_by_asset_set =
      from(d in ContinueDismissal,
        where: d.user_id == ^user_id,
        select: {d.asset_set_id, d.dismissed_at}
      )
      |> Repo.all()
      |> Map.new()

    user_id
    |> list_recent(limit: @default_recent_limit)
    |> Enum.reject(fn %{asset_set_id: id, last_played_at: last_played_at} ->
      case Map.get(dismissed_at_by_asset_set, id) do
        nil ->
          false

        dismissed_at ->
          not (last_played_at && DateTime.compare(last_played_at, dismissed_at) == :gt)
      end
    end)
  end

  @doc """
  Dismisses `asset_set_id` from `user_id`'s Continue. `id` is the
  dismissal row's client-supplied primary key. Idempotent: dismissing
  an already-dismissed game converges on the existing row and leaves
  it dismissed either way.
  """
  @spec dismiss_continue(pos_integer(), Ecto.UUID.t(), Ecto.UUID.t()) ::
          {:ok, ContinueDismissal.t()} | {:error, term()}
  def dismiss_continue(user_id, id, asset_set_id) do
    with :ok <- verify_asset_set_ownership(user_id, asset_set_id) do
      changeset =
        ContinueDismissal.create_changeset(%ContinueDismissal{}, %{
          id: id,
          user_id: user_id,
          asset_set_id: asset_set_id,
          dismissed_at: DateTime.utc_now() |> DateTime.truncate(:microsecond)
        })

      Ecto.Multi.new()
      |> Ecto.Multi.insert(:dismissal, changeset,
        on_conflict: {:replace, [:dismissed_at, :updated_at]},
        conflict_target: [:user_id, :asset_set_id],
        returning: true
      )
      |> Ecto.Multi.run(:journal, fn _repo, %{dismissal: dismissal} ->
        ChangeJournal.append(user_id, :curation, dismissal.id, CurationPayload.build(dismissal))
      end)
      |> Repo.transaction()
      |> case do
        {:ok, %{dismissal: dismissal}} -> {:ok, dismissal}
        {:error, _step, reason, _changes} -> {:error, reason}
      end
    end
  end

  @doc """
  Explicitly un-dismisses `asset_set_id` for `user_id` -- distinct from
  the automatic recovery-by-replay `list_continue/1` performs. `id` is
  accepted for interface symmetry with the rest of this module's
  mutation functions but unused: the row being removed is identified
  by `(user_id, asset_set_id)`, the same natural key
  `dismiss_continue/3` converges on. A no-op if not currently
  dismissed.
  """
  @spec undismiss_continue(pos_integer(), Ecto.UUID.t() | nil, Ecto.UUID.t()) ::
          {:ok, :removed} | {:error, term()}
  def undismiss_continue(user_id, _id, asset_set_id) do
    case get_by_safe(ContinueDismissal, user_id: user_id, asset_set_id: asset_set_id) do
      nil ->
        {:ok, :removed}

      %ContinueDismissal{} = dismissal ->
        Ecto.Multi.new()
        |> Ecto.Multi.delete(:dismissal, dismissal)
        |> Ecto.Multi.run(:journal, fn _repo, %{dismissal: dismissal} ->
          ChangeJournal.tombstone(user_id, :curation, dismissal.id)
        end)
        |> Repo.transaction()
        |> case do
          {:ok, _changes} -> {:ok, :removed}
          {:error, _step, reason, _changes} -> {:error, reason}
        end
    end
  end

  # Re-derives the compact `recent` summary for one game from its
  # current play sessions and appends it under the game's asset_set_id
  # -- called inside the same transaction as every session
  # record/delete so Recent never drifts from the sessions it derives
  # from.
  defp journal_recent(user_id, asset_set_id) do
    last_played_at =
      from(s in PlaySession,
        where: s.user_id == ^user_id and s.asset_set_id == ^asset_set_id,
        order_by: [desc: s.started_at],
        limit: 1,
        select: s.started_at
      )
      |> Repo.one()

    ChangeJournal.append(
      user_id,
      :curation,
      asset_set_id,
      CurationPayload.build(%{
        type: :recent,
        asset_set_id: asset_set_id,
        last_played_at: last_played_at
      })
    )
  end

  # --- shared internals ---

  # T-03-11/T-03-13: every referenced asset set is re-checked against
  # the calling user, regardless of whether the id is well-formed —
  # a guessed or reused id from another user must never resolve.
  defp verify_asset_set_ownership(user_id, asset_set_id) do
    case get_by_safe(AssetSet, id: asset_set_id, user_id: user_id) do
      nil -> {:error, :not_found}
      %AssetSet{} -> :ok
    end
  end

  defp verify_collection_ownership(user_id, collection_id) do
    case get_by_safe(Collection, id: collection_id, user_id: user_id) do
      nil -> {:error, :not_found}
      %Collection{} = collection -> {:ok, collection}
    end
  end

  defp fetch_collection_member(collection_id, asset_set_id) do
    case get_by_safe(CollectionMember, collection_id: collection_id, asset_set_id: asset_set_id) do
      nil -> {:error, :not_found}
      %CollectionMember{} = member -> {:ok, member}
    end
  end

  defp fetch_queue_item(user_id, asset_set_id) do
    case get_by_safe(QueueItem, user_id: user_id, asset_set_id: asset_set_id) do
      nil -> {:error, :not_found}
      %QueueItem{} = item -> {:ok, item}
    end
  end

  # P5-WR-002: every id above is a client-controlled path segment cast
  # into a `binary_id`/UUID-typed Ecto field. `Repo.get_by/2` raises
  # `Ecto.Query.CastError` at query-build time for a malformed value
  # (unlike `Ecto.Changeset.cast/3`, which returns an invalid
  # changeset) — that used to surface as a raw exception (and,
  # depending on the rescue path, a generic 500) instead of the
  # correctness-appropriate "not found". Treat a bad cast exactly like
  # "no matching row".
  defp get_by_safe(queryable, clauses) do
    Repo.get_by(queryable, clauses)
  rescue
    Ecto.Query.CastError -> nil
  end

  # P5-CR-001: `Position.between/2` requires `low < high` and otherwise
  # loops forever growing precision. Neighbour positions are resolved
  # from client-supplied ids, so their relative order is never
  # guaranteed — validate it here, before ever calling
  # `Position.needs_rebalance?/2` or `Position.between/2`, rather than
  # trusting the caller. `nil` (meaning "start"/"end" of the list) is
  # always fine on either side.
  defp validate_neighbour_order(nil, _after_pos), do: :ok
  defp validate_neighbour_order(_before_pos, nil), do: :ok

  defp validate_neighbour_order(before_pos, after_pos) do
    if before_pos < after_pos do
      :ok
    else
      {:error,
       {:curation_invalid_position,
        "The before/after neighbours must be distinct and in ascending order."}}
    end
  end

  defp resolve_member_neighbour(_collection_id, nil), do: {:ok, nil}

  defp resolve_member_neighbour(collection_id, asset_set_id) do
    case fetch_collection_member(collection_id, asset_set_id) do
      {:ok, member} -> {:ok, member.position}
      {:error, reason} -> {:error, reason}
    end
  end

  defp resolve_queue_neighbour(_user_id, nil), do: {:ok, nil}

  defp resolve_queue_neighbour(user_id, asset_set_id) do
    case fetch_queue_item(user_id, asset_set_id) do
      {:ok, item} -> {:ok, item.position}
      {:error, reason} -> {:error, reason}
    end
  end

  defp reposition_member(_user_id, %CollectionMember{position: position} = member, position) do
    {:ok, member}
  end

  defp reposition_member(user_id, %CollectionMember{} = member, new_position) do
    changeset = CollectionMember.reposition_changeset(member, %{position: new_position})

    Ecto.Multi.new()
    |> Ecto.Multi.update(:member, changeset)
    |> Ecto.Multi.run(:journal, fn _repo, %{member: member} ->
      ChangeJournal.append(user_id, :curation, member.id, CurationPayload.build(member))
    end)
    |> Repo.transaction()
    |> case do
      {:ok, %{member: member}} -> {:ok, member}
      {:error, _step, reason, _changes} -> {:error, reason}
    end
  end

  defp reposition_queue_item(_user_id, %QueueItem{position: position} = item, position) do
    {:ok, item}
  end

  defp reposition_queue_item(user_id, %QueueItem{} = item, new_position) do
    changeset = QueueItem.reposition_changeset(item, %{position: new_position})

    Ecto.Multi.new()
    |> Ecto.Multi.update(:item, changeset)
    |> Ecto.Multi.run(:journal, fn _repo, %{item: item} ->
      ChangeJournal.append(user_id, :curation, item.id, CurationPayload.build(item))
    end)
    |> Repo.transaction()
    |> case do
      {:ok, %{item: item}} -> {:ok, item}
      {:error, _step, reason, _changes} -> {:error, reason}
    end
  end

  # Reassigns evenly spaced positions in the current visible order,
  # returning the possibly-updated members/items. Called both
  # standalone (wrapped in its own transaction by the public
  # `rebalance_*` functions) and inline from a move that already
  # opened its own transaction — never opens a transaction itself.
  defp do_rebalance_collection(user_id, collection_id) do
    members =
      from(m in CollectionMember,
        where: m.collection_id == ^collection_id,
        order_by: [asc: m.position]
      )
      |> Repo.all()

    reassign(
      members,
      Position.spaced(length(members)),
      &CollectionMember.reposition_changeset/2,
      user_id
    )
  end

  defp do_rebalance_queue(user_id) do
    items =
      from(i in QueueItem, where: i.user_id == ^user_id, order_by: [asc: i.position])
      |> Repo.all()

    reassign(items, Position.spaced(length(items)), &QueueItem.reposition_changeset/2, user_id)
  end

  defp reassign(rows, new_positions, reposition_changeset_fun, user_id) do
    rows
    |> Enum.zip(new_positions)
    |> Enum.reduce_while({:ok, []}, fn {row, new_position}, {:ok, acc} ->
      if row.position == new_position do
        {:cont, {:ok, [row | acc]}}
      else
        changeset = reposition_changeset_fun.(row, %{position: new_position})

        with {:ok, updated} <- Repo.update(changeset),
             {:ok, _entry} <-
               ChangeJournal.append(
                 user_id,
                 :curation,
                 updated.id,
                 CurationPayload.build(updated)
               ) do
          {:cont, {:ok, [updated | acc]}}
        else
          {:error, reason} -> {:halt, {:error, reason}}
        end
      end
    end)
    |> case do
      {:ok, acc} -> {:ok, Enum.reverse(acc)}
      {:error, reason} -> {:error, reason}
    end
  end

  defp max_position(Collection, user_id: user_id) do
    from(c in Collection,
      where: c.user_id == ^user_id,
      order_by: [desc: c.position],
      limit: 1,
      select: c.position
    )
    |> Repo.one()
  end

  defp max_position(CollectionMember, collection_id: collection_id) do
    from(m in CollectionMember,
      where: m.collection_id == ^collection_id,
      order_by: [desc: m.position],
      limit: 1,
      select: m.position
    )
    |> Repo.one()
  end

  defp max_position(QueueItem, user_id: user_id) do
    from(i in QueueItem,
      where: i.user_id == ^user_id,
      order_by: [desc: i.position],
      limit: 1,
      select: i.position
    )
    |> Repo.one()
  end

  # P5-WR-001: takes a Postgres transaction-scoped advisory lock keyed
  # on `{resource, key}` so a concurrent cap-check-then-insert for the
  # same resource (e.g. the same user's collections, or the same
  # collection's members) serializes behind whichever request acquires
  # it first, rather than racing on a plain read-then-write. The lock
  # is released automatically at transaction commit/rollback.
  defp acquire_cap_lock(repo, resource, key) do
    repo.query!("SELECT pg_advisory_xact_lock($1)", [advisory_lock_key(resource, key)])
    {:ok, :locked}
  end

  # P5-WR-005: takes the same transaction-scoped advisory lock as
  # `acquire_cap_lock/3` but for callers already inside a
  # `Repo.transaction/1` block (rather than building an `Ecto.Multi`),
  # e.g. the move/reorder read-resolve-write sequences. Blocks a
  # concurrent mover for the same resource until this transaction
  # commits or rolls back, rather than letting both work from a stale
  # read of the neighbours' positions.
  defp lock_resource!(resource, key) do
    Repo.query!("SELECT pg_advisory_xact_lock($1)", [advisory_lock_key(resource, key)])
    :ok
  end

  defp advisory_lock_key(resource, key), do: :erlang.phash2({resource, key})

  # `check_*_cap/1,2` return a plain `:ok | {:error, _}`, but
  # `Ecto.Multi.run/3` callbacks must return `{:ok, _} | {:error, _}`.
  defp as_multi_result(:ok), do: {:ok, :ok}
  defp as_multi_result({:error, _reason} = error), do: error

  defp check_collection_cap(user_id) do
    count = Repo.aggregate(from(c in Collection, where: c.user_id == ^user_id), :count)

    if count >= @collection_cap do
      {:error, {:curation_limit_exceeded, "The collection limit has been reached."}}
    else
      :ok
    end
  end

  defp check_member_cap(collection_id, asset_set_id) do
    exists? =
      Repo.exists?(
        from(m in CollectionMember,
          where: m.collection_id == ^collection_id and m.asset_set_id == ^asset_set_id
        )
      )

    if exists? do
      :ok
    else
      count =
        Repo.aggregate(
          from(m in CollectionMember, where: m.collection_id == ^collection_id),
          :count
        )

      if count >= @member_cap do
        {:error, {:curation_limit_exceeded, "The collection member limit has been reached."}}
      else
        :ok
      end
    end
  end

  defp check_queue_cap(user_id, asset_set_id) do
    exists? =
      Repo.exists?(
        from(i in QueueItem, where: i.user_id == ^user_id and i.asset_set_id == ^asset_set_id)
      )

    if exists? do
      :ok
    else
      count = Repo.aggregate(from(i in QueueItem, where: i.user_id == ^user_id), :count)

      if count >= @queue_cap do
        {:error, {:curation_limit_exceeded, "The queue limit has been reached."}}
      else
        :ok
      end
    end
  end
end
