defmodule Playstead.Curation do
  @moduledoc """
  The user-scoped curation context (D-07…D-10): Favorites, Collections,
  the play queue, Continue dismissals, and coarse play sessions. Every
  public function takes the owning user id first and every query
  filters on it (T-03-11) — a curation row or its referenced asset set
  belonging to another user is never visible here, it is a 404.

  Every mutation follows the same discipline `Playstead.Idempotency`
  and `Playstead.Sync.ChangeJournal`'s moduledocs require: the row
  write and its journal entry (`ChangeJournal.append/4` or
  `tombstone/3`) happen inside one `Ecto.Multi`, never a separate
  transaction — a post-commit append could let a client miss the
  change permanently.

  The Mac client and the LiveView console both call this module; there
  is no second implementation of curation logic anywhere else.
  """

  import Ecto.Query, warn: false

  alias Playstead.Catalogue.AssetSet
  alias Playstead.Curation.Favorite
  alias Playstead.Repo
  alias Playstead.Sync.{ChangeJournal, CurationPayload}

  @doc """
  Favorites `asset_set_id` for `user_id`, using `id` as the row's
  client-supplied primary key. Idempotent by nature: a repeated intent
  (even under a different `id`) converges on the same row via the
  `(user_id, asset_set_id)` unique index and leaves exactly one row.
  Returns `{:error, :not_found}` if `asset_set_id` does not belong to
  `user_id`.
  """
  @spec add_favorite(pos_integer(), Ecto.UUID.t(), Ecto.UUID.t()) ::
          {:ok, Favorite.t()} | {:error, term()}
  def add_favorite(user_id, id, asset_set_id) do
    with :ok <- verify_asset_set_ownership(user_id, asset_set_id) do
      changeset =
        Favorite.create_changeset(%Favorite{}, %{
          id: id,
          user_id: user_id,
          asset_set_id: asset_set_id
        })

      # `returning: true` is load-bearing (mirrors Pairing.insert_credential/3's
      # D-20b comment): the primary key is client-supplied, not
      # autogenerated, so without an explicit RETURNING Ecto just hands
      # back the submitted changeset verbatim instead of the row that
      # actually persisted — on a conflict that would silently return
      # the caller's new id instead of the pre-existing row's.
      Ecto.Multi.new()
      |> Ecto.Multi.insert(:favorite, changeset,
        on_conflict: {:replace, [:updated_at]},
        conflict_target: [:user_id, :asset_set_id],
        returning: true
      )
      |> Ecto.Multi.run(:journal, fn _repo, %{favorite: favorite} ->
        ChangeJournal.append(user_id, :curation, favorite.id, CurationPayload.build(favorite))
      end)
      |> Repo.transaction()
      |> case do
        {:ok, %{favorite: favorite}} -> {:ok, favorite}
        {:error, _step, reason, _changes} -> {:error, reason}
      end
    end
  end

  @doc """
  Removes `user_id`'s favorite of `asset_set_id`, appending a tombstone
  journal entry with an empty payload in the same transaction.
  Removing a favorite that does not exist is accepted and treated as
  success (D-09's toggle idempotency) — there is nothing to tombstone,
  and nothing observable changes either way.
  """
  @spec remove_favorite(pos_integer(), Ecto.UUID.t()) :: {:ok, :removed} | {:error, term()}
  def remove_favorite(user_id, asset_set_id) do
    case Repo.get_by(Favorite, user_id: user_id, asset_set_id: asset_set_id) do
      nil ->
        {:ok, :removed}

      %Favorite{} = favorite ->
        Ecto.Multi.new()
        |> Ecto.Multi.delete(:favorite, favorite)
        |> Ecto.Multi.run(:journal, fn _repo, %{favorite: favorite} ->
          ChangeJournal.tombstone(user_id, :curation, favorite.id)
        end)
        |> Repo.transaction()
        |> case do
          {:ok, _changes} -> {:ok, :removed}
          {:error, _step, reason, _changes} -> {:error, reason}
        end
    end
  end

  @doc "Lists `user_id`'s favorites, oldest row-id first."
  @spec list_favorites(pos_integer()) :: [Favorite.t()]
  def list_favorites(user_id) do
    from(f in Favorite, where: f.user_id == ^user_id, order_by: [asc: f.id])
    |> Repo.all()
  end

  # T-03-11/T-03-13: every referenced asset set is re-checked against
  # the calling user, regardless of whether the id is well-formed —
  # a guessed or reused id from another user must never resolve.
  defp verify_asset_set_ownership(user_id, asset_set_id) do
    case Repo.get_by(AssetSet, id: asset_set_id, user_id: user_id) do
      nil -> {:error, :not_found}
      %AssetSet{} -> :ok
    end
  end
end
