defmodule Playstead.Saves do
  @moduledoc """
  The user-scoped saves bounded context (D-25, D-26): save lines and
  their immutable revision DAG. Every public function takes the owning
  user id (or scopes through it) and every query filters on it, the
  same discipline `Playstead.Curation` follows.

  `commit_revision/3` performs D-26's exact four-step commit order
  inside one `Ecto.Multi`, never a separate transaction: resolve-or-
  insert the save line, commit the pending blob through
  `Playstead.Blobs` (never through the store directly, never
  reimplementing the store's own durable-write discipline), insert the
  `save_revisions` row, then
  append the `save` journal entry through the same `ChangeJournal` call
  `Playstead.Curation` uses. The idempotency receipt itself is written
  by `Playstead.Idempotency.execute/4` around the whole thing at the
  controller layer, exactly like `PlaysteadWeb.Api.V1.CurationController`
  -- this context knows nothing of idempotency receipts, and it knows
  nothing of CAS layout: `blobs` learns nothing about saves either.
  """

  import Ecto.Query, warn: false

  alias Playstead.Blobs
  alias Playstead.Repo
  alias Playstead.Saves.{PendingUpload, Revision, Save}
  alias Playstead.Sync.{ChangeJournal, SavePayload}

  # D-16: how long a streamed-upload's blob digest stays claimable by a
  # matching metadata commit before it is considered abandoned. A sweep
  # job for expired rows is out of scope for this plan (T-04-04-07).
  @pending_upload_ttl_seconds 3600

  @doc """
  Records that `command_id`'s streamed upload (already committed into
  the CAS by the caller) produced `blob_sha256`/`size_bytes`, so the
  metadata-commit half can find it without the client resending the
  digest. Idempotent: re-uploading the same `command_id` (e.g. a
  retried PUT) replaces the pointer with the latest result.
  """
  @spec record_pending_upload(pos_integer(), binary(), binary(), String.t(), non_neg_integer()) ::
          {:ok, PendingUpload.t()} | {:error, term()}
  def record_pending_upload(user_id, device_id, command_id, blob_sha256, size_bytes) do
    attrs = %{
      id: command_id,
      user_id: user_id,
      device_id: device_id,
      blob_sha256: blob_sha256,
      size_bytes: size_bytes,
      expires_at: DateTime.utc_now() |> DateTime.truncate(:second) |> DateTime.add(@pending_upload_ttl_seconds, :second)
    }

    %PendingUpload{}
    |> PendingUpload.create_changeset(attrs)
    |> Repo.insert(
      on_conflict: {:replace, [:blob_sha256, :size_bytes, :expires_at, :updated_at]},
      conflict_target: [:id],
      returning: true
    )
  end

  @doc """
  Commits one revision for `user_id`, captured by `device`, per
  `attrs` (string-keyed, mirroring the other contexts' controller
  boundary). `attrs` must include `"command_id"` (naming the
  already-uploaded pending blob), `"id"` (the client-supplied revision
  id), and `"content_key"`; `"save_kind"` and `"slot"` default to
  `"battery"`/`"0"` (D-10). Returns `{:error, :not_found}` if
  `command_id` names no live pending upload for this user.
  """
  @spec commit_revision(pos_integer(), map(), map()) :: {:ok, Revision.t()} | {:error, term()}
  def commit_revision(user_id, device, attrs) do
    with {:ok, pending} <- fetch_pending_upload(user_id, get(attrs, "command_id")) do
      content_key = get(attrs, "content_key")
      save_kind = get(attrs, "save_kind") || "battery"
      slot = get(attrs, "slot") || "0"
      revision_id = get(attrs, "id") || Ecto.UUID.generate()
      line_id = Ecto.UUID.generate()
      now = DateTime.utc_now() |> DateTime.truncate(:microsecond)

      line_changeset =
        Save.create_changeset(%Save{}, %{
          id: line_id,
          user_id: user_id,
          content_key: content_key,
          save_kind: save_kind,
          slot: slot
        })

      Ecto.Multi.new()
      # `returning: true` is load-bearing (mirrors `Curation.add_favorite/3`):
      # the primary key is client-generated, not autogenerated, so a
      # conflict must hand back the pre-existing line's real id, not the
      # id this call happened to try.
      |> Ecto.Multi.insert(:line, line_changeset,
        on_conflict: {:replace, [:updated_at]},
        conflict_target: [:user_id, :content_key, :save_kind, :slot],
        returning: true
      )
      |> Ecto.Multi.run(:blob, fn _repo, _changes ->
        if Blobs.exists?(pending.blob_sha256) do
          {:ok, pending}
        else
          {:error, {:save_revision_digest_mismatch, "The uploaded blob could not be found."}}
        end
      end)
      |> Ecto.Multi.insert(:revision, fn %{line: line} ->
        Revision.create_changeset(%Revision{}, %{
          id: revision_id,
          user_id: user_id,
          save_line_id: line.id,
          parent_revision_id: get(attrs, "parent_revision_id"),
          blob_sha256: pending.blob_sha256,
          size_bytes: pending.size_bytes,
          origin_device_id: device.id,
          device_captured_at: get(attrs, "device_captured_at"),
          recorded_at: now,
          capture_method: get(attrs, "capture_method"),
          adapter_id: get(attrs, "adapter_id"),
          adapter_version: get(attrs, "adapter_version"),
          save_format: get(attrs, "save_format"),
          format_confidence: get(attrs, "format_confidence"),
          play_session_id: get(attrs, "play_session_id")
        })
      end)
      |> Ecto.Multi.run(:journal, fn _repo, %{line: line, revision: revision} ->
        ChangeJournal.append(user_id, :save, revision.id, SavePayload.build(revision, line))
      end)
      |> Repo.transaction()
      |> case do
        {:ok, %{revision: revision}} -> {:ok, revision}
        {:error, _step, reason, _changes} -> {:error, reason}
      end
    end
  end

  @doc "Fetches the live (unexpired) pending upload for `user_id`/`command_id`."
  @spec fetch_pending_upload(pos_integer(), binary() | nil) ::
          {:ok, PendingUpload.t()} | {:error, :not_found}
  def fetch_pending_upload(_user_id, nil), do: {:error, :not_found}

  def fetch_pending_upload(user_id, command_id) do
    now = DateTime.utc_now() |> DateTime.truncate(:second)

    query =
      from(p in PendingUpload,
        where: p.id == ^command_id and p.user_id == ^user_id and p.expires_at > ^now
      )

    case Repo.one(query) do
      nil -> {:error, :not_found}
      %PendingUpload{} = pending -> {:ok, pending}
    end
  end

  @doc "Fetches a revision (owned by `user_id`) by its id, or `nil`."
  @spec get_revision(pos_integer(), binary()) :: Revision.t() | nil
  def get_revision(user_id, revision_id) do
    Repo.get_by(Revision, id: revision_id, user_id: user_id)
  end

  defp get(attrs, key) when is_map(attrs), do: Map.get(attrs, key) || Map.get(attrs, String.to_atom(key))
end
